spring:
  application:
    name: project_mobile_be

  datasource:
    url: jdbc:mysql://localhost:3306/mobileproject
    username: "root"
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  server:
    port: 8080
